name: Test Rego Policies

on:
  push:
    paths:
      - 'Terraform_Examples/resource_files/data_label_rego/*'
      - '.github/workflows/opa.yaml'

jobs:
  Run-OPA-Tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - Terraform_Examples/resource_files/data_label_rego

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Setup OPA
      uses: open-policy-agent/setup-opa@v2
      with:
        version: latest

    - name: Run Rego Policy Tests
      run: opa test ${{ matrix.package }} -v
      
